import { Inter } from 'next/font/google'
import '@/styles/globals.css';
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tipsy Turtles NextJs Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        </body>
    </html>
  )
}
