import Header from '@/components/Header'
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Tipsy Turtles NextJs Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>{children}</div>
        <Footer />
        </body>
    </html>
  )
}
